# Generated by Django 5.2.12 on 2026-03-23 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_name', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('income_expense', 'Отчет по доходам и расходам'), ('cash_flow', 'Банковская выписка / ДДС'), ('budget', 'Бюджет подразделения'), ('kpi', 'KPI-отчет подразделения')], max_length=30)),
                ('period', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('uploaded', 'Загружен'), ('validating', 'Проверяется'), ('analyzing', 'Анализируется'), ('done', 'Проанализирован'), ('error', 'Ошибка')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_inflow', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_outflow', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_flow', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('chart_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='dashboard.document')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('record_type', models.CharField(blank=True, max_length=50)),
                ('counterparty', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('indicator', models.CharField(blank=True, max_length=255)),
                ('plan_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fact_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('period', models.CharField(blank=True, max_length=100)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dashboard.document')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='dashboard.document')),
            ],
        ),
    ]
